version: '3.7'
services:
  app:
    build: .
    tty: true
    restart: always
    ports:
      - 3000:3000
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/myapp
    command: yarn run start
    networks:
      - webnet
    depends_on:
      - redis
      - cassandra
  cassandra:
    image: cassandra:latest
    ports:
      - 9044:9042
    environment:
      CASSANDRA_USER: user
      CASSANDRA_PASSWORD: password
      MAX_HEAP_SIZE: 256M
      HEAP_NEWSIZE: 128M
    restart: always
    volumes:
      - cddata:/var/lib/cassandra
  redis:
    #container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - webnet
networks:
  webnet:
volumes:
  cddata:
